### ISSUE TITLE
Retrain step needs double quotes if running on Windows

### ISSUE THREAD

**Issue by rluppi** [whatrocks/cozmo-tensorflow#1]
I’ve spent quite some time to pass beyond the retrain step. The error was not much helpful, but I’ve found out that the python command must be in double quotes like below if you are running on Windows:

floyd run \
  --gpu \
  --data whatrocks/datasets/cozmo-images:data \
  "python retrain.py --image_dir /data"

**Comment by whatrocks** [comment]
Great catch, thank you ! I've updated the README
